trigger: none

parameters:
- name: dataStage
  type: string
  displayName: dataStage
  default: IaC
  values:
  - IaC
  - Initial data

resources:
  repositories:
  - repository: templates
    name: GCIT-Agile/infra-gcloud
    type: git
    ref: feature/funnel

variables:
  - template: variables/vars-azure-pipeline.yml

extends:
  template: pipeline/main.yml@templates
  parameters:
      dataStage: ${{ parameters.dataStage }}

