[dev]

[dev.variables]

raw_bucket_name = "co-grupo-exito-funnel-mercd-raw-data-dev"
trusted_bucket_name = "co-grupo-exito-funnel-mercd-trusted-data-dev"
project = "co-grupoexito-funnel-mercd-dev"
error_folder = "co-grupo-exito-error-data"
data_folder = "co-grupo-exito-raw-data"

[dev.paths.entity_names]

analytical_model = "ANALYTICAL_MODEL"
analytical_model_backup = "ANALYTICAL_MODEL_BACKUP"
contactabilidad = "CONTACTABILIDAD"
contactabilidad_backup = "CONTACTABILIDAD_BACKUP"
dim_modelo_segmento = "DIM_MODELO_SEGMENTO"
dim_modelo_segmento_backup = "DIM_MODELO_SEGMENTO_BACKUP"
fact_days = "FACT_DAYS"
fact_months = "FACT_MONTHS"
fact_target_days = "FACT_TARGET_DAYS"
fact_target_months = "FACT_TARGET_MONTHS"
fact_target_years = "FACT_TARGET_YEARS"
model_run = "MODEL_RUN"
model_run_backup = "MODEL_RUN_BACKUP"
segmentacion = "SEGMENTACION"
segmentacion_backup = "SEGMENTACION_BACKUP"

# -------------------------------- PREFIXES --------------------------------------------------

[dev.paths.raw_path_prefix.teradata]

data_folder = """\
    @format \
    gs://{this.variables.raw_bucket_name}/\
    {this.variables.data_folder}/\
    {this.origin.teradata}/\
    {this.business_domain}\
"""
error_folder = """\
    @format \
    gs://{this.variables.raw_bucket_name}/\
    {this.variables.error_folder}/\
    {this.origin.teradata}/\
    {this.business_domain}\
"""

[dev.paths.raw_path_prefix.excel]

data_folder = """\
    @format \
    gs://{this.variables.raw_bucket_name}/\
    {this.variables.data_folder}/\
    {this.origin.excel}/\
    {this.business_domain}\
"""
error_folder = """\
    @format \
    gs://{this.variables.raw_bucket_name}/\
    {this.variables.error_folder}/\
    {this.origin.excel}/\
    {this.business_domain}\
"""

[dev.paths.trusted_path_prefix.teradata]

data_folder = "@format gs://{this.variables.trusted_bucket_name}/{this.origin.teradata}/{this.business_domain}"

[dev.paths.trusted_path_prefix.excel]

data_folder = "@format gs://{this.variables.trusted_bucket_name}/{this.origin.excel}/{this.business_domain}"

# ---------------------------------- PATHS -------------------------------------------------

[dev.paths.analytical_model]
raw_data_path = "@format {this.paths.raw_path_prefix.teradata.data_folder}/{this.paths.entity_names.analytical_model}"
error_data_path = "@format {this.paths.raw_path_prefix.teradata.error_folder}/{this.paths.entity_names.analytical_model}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.teradata.data_folder}/{this.paths.entity_names.analytical_model}"

[dev.paths.analytical_model_backup]
raw_data_path = "@format {this.paths.raw_path_prefix.teradata.data_folder}/{this.paths.entity_names.analytical_model_backup}"
error_data_path = "@format {this.paths.raw_path_prefix.teradata.error_folder}/{this.paths.entity_names.analytical_model_backup}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.teradata.data_folder}/{this.paths.entity_names.analytical_model_backup}"

[dev.paths.contactabilidad]

raw_data_path = "@format {this.paths.raw_path_prefix.teradata.data_folder}/{this.paths.entity_names.contactabilidad}"
error_data_path = "@format {this.paths.raw_path_prefix.teradata.error_folder}/{this.paths.entity_names.contactabilidad}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.teradata.data_folder}/{this.paths.entity_names.contactabilidad}"

[dev.paths.contactabilidad_backup]

raw_data_path = "@format {this.paths.raw_path_prefix.teradata.data_folder}/{this.paths.entity_names.contactabilidad_backup}"
error_data_path = "@format {this.paths.raw_path_prefix.teradata.error_folder}/{this.paths.entity_names.contactabilidad_backup}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.teradata.data_folder}/{this.paths.entity_names.contactabilidad_backup}"

[dev.paths.dim_modelo_segmento]

raw_data_path = "@format {this.paths.raw_path_prefix.teradata.data_folder}/{this.paths.entity_names.dim_modelo_segmento}"
error_data_path = "@format {this.paths.raw_path_prefix.teradata.error_folder}/{this.paths.entity_names.dim_modelo_segmento}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.teradata.data_folder}/{this.paths.entity_names.dim_modelo_segmento}"

[dev.paths.dim_modelo_segmento_backup]

raw_data_path = "@format {this.paths.raw_path_prefix.teradata.data_folder}/{this.paths.entity_names.dim_modelo_segmento_backup}"
error_data_path = "@format {this.paths.raw_path_prefix.teradata.error_folder}/{this.paths.entity_names.dim_modelo_segmento_backup}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.teradata.data_folder}/{this.paths.entity_names.dim_modelo_segmento_backup}"

[dev.paths.fact_days]

raw_data_path = "@format {this.paths.raw_path_prefix.excel.data_folder}/{this.paths.entity_names.fact_days}"
error_data_path = "@format {this.paths.raw_path_prefix.excel.error_folder}/{this.paths.entity_names.fact_days}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.excel.data_folder}/{this.paths.entity_names.fact_days}"

[dev.paths.fact_months]

raw_data_path = "@format {this.paths.raw_path_prefix.excel.data_folder}/{this.paths.entity_names.fact_months}"
error_data_path = "@format {this.paths.raw_path_prefix.excel.error_folder}/{this.paths.entity_names.fact_months}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.excel.data_folder}/{this.paths.entity_names.fact_months}"

[dev.paths.fact_target_days]

raw_data_path = "@format {this.paths.raw_path_prefix.excel.data_folder}/{this.paths.entity_names.fact_target_days}"
error_data_path = "@format {this.paths.raw_path_prefix.excel.error_folder}/{this.paths.entity_names.fact_target_days}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.excel.data_folder}/{this.paths.entity_names.fact_target_days}"

[dev.paths.fact_target_months]

raw_data_path = "@format {this.paths.raw_path_prefix.excel.data_folder}/{this.paths.entity_names.fact_target_months}"
error_data_path = "@format {this.paths.raw_path_prefix.excel.error_folder}/{this.paths.entity_names.fact_target_months}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.excel.data_folder}/{this.paths.entity_names.fact_target_months}"

[dev.paths.fact_target_years]

raw_data_path = "@format {this.paths.raw_path_prefix.excel.data_folder}/{this.paths.entity_names.fact_target_years}"
error_data_path = "@format {this.paths.raw_path_prefix.excel.error_folder}/{this.paths.entity_names.fact_target_years}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.excel.data_folder}/{this.paths.entity_names.fact_target_years}"

[dev.paths.model_run]
raw_data_path = "@format {this.paths.raw_path_prefix.teradata.data_folder}/{this.paths.entity_names.model_run}"
error_data_path = "@format {this.paths.raw_path_prefix.teradata.error_folder}/{this.paths.entity_names.model_run}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.teradata.data_folder}/{this.paths.entity_names.model_run}"

[dev.paths.model_run_backup]
raw_data_path = "@format {this.paths.raw_path_prefix.teradata.data_folder}/{this.paths.entity_names.model_run_backup}"
error_data_path = "@format {this.paths.raw_path_prefix.teradata.error_folder}/{this.paths.entity_names.model_run_backup}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.teradata.data_folder}/{this.paths.entity_names.model_run_backup}"

[dev.paths.segmentacion]
raw_data_path = "@format {this.paths.raw_path_prefix.teradata.data_folder}/{this.paths.entity_names.segmentacion}"
error_data_path = "@format {this.paths.raw_path_prefix.teradata.error_folder}/{this.paths.entity_names.segmentacion}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.teradata.data_folder}/{this.paths.entity_names.segmentacion}"

[dev.paths.segmentacion_backup]
raw_data_path = "@format {this.paths.raw_path_prefix.teradata.data_folder}/{this.paths.entity_names.segmentacion_backup}"
error_data_path = "@format {this.paths.raw_path_prefix.teradata.error_folder}/{this.paths.entity_names.segmentacion_backup}"
trusted_data_path = "@format {this.paths.trusted_path_prefix.teradata.data_folder}/{this.paths.entity_names.segmentacion_backup}"




