jobs:
  - pysparkJob:
      args:
        #- --trusted_flows=dim_modelo_segmento
        - --env=qa
        - --granularity=YEAR
        - --execution_type=delta
      jarFileUris:
        - gs://co-grupo-exito-funnel-mercd-app-data-qa/app_files/dist/dev.toml
        - gs://co-grupo-exito-funnel-mercd-app-data-qa/app_files/dist/default.toml
        - gs://co-grupo-exito-funnel-mercd-app-data-qa/app_files/dist/pdn.toml
        - gs://co-grupo-exito-funnel-mercd-app-data-qa/app_files/dist/qa.toml
      mainPythonFileUri: gs://co-grupo-exito-funnel-mercd-app-data-qa/app_files/dist/main.py
      properties:
        spark.app.name: trusted_workflow_qa
        spark.jars.packages: "io.delta:delta-spark_2.12:3.0.0"
        spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
        spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
        spark.databricks.delta.properties.defaults.enableChangeDataFeed: "false"
        spark.databricks.delta.retentionDurationCheck.enabled: "false"
        spark.databricks.delta.autoCompact.enabled: "auto"
        spark.databricks.delta.optimizeWrites.enabled: "true"
        spark.databricks.delta.properties.defaults.targetFileSize: "10485760"
        spark.databricks.delta.optimize.repartition.enabled: "true"
        spark.executor.heartbeatInterval: '100000'
        spark.network.timeout: '300'
        spark.sql.debug.maxToStringFields: '150'
        spark.sql.parquet.int96RebaseModeInWrite: LEGACY
        spark.sql.shuffle.partitions: '64'
        spark.sql.files.ignoreCorruptFiles: 'true'
        spark.sql.parquet.datetimeRebaseModeInWrite: CORRECTED
        spark.sql.autoBroadcastJoinThreshold: '-1'
        spark.sql.adaptive.enabled: 'false'
      pythonFileUris:
        - gs://co-grupo-exito-funnel-mercd-app-data-qa/app_files/dist/bubbaloo.zip
        - gs://co-grupo-exito-funnel-mercd-app-data-qa/app_files/dist/flows.zip
    stepId: dp-funnel-mercd-job-qa
placement:
  managedCluster:
    clusterName: dp-funnel-mercd-pipeline-qa
    config:
      configBucket: co-grupo-exito-funnel-mercd-app-data-qa
      gceClusterConfig:
        networkUri: default
        serviceAccountScopes:
          - https://www.googleapis.com/auth/cloud-platform
        zoneUri: us-central1-a
      masterConfig:
        diskConfig:
          bootDiskSizeGb: 150
          bootDiskType: pd-standard
          localSsdInterface: SCSI
        machineTypeUri: n2-standard-8
        numInstances: 1
      softwareConfig:
        imageVersion: 2.2-debian12
        properties:
          dataproc:dataproc.allow.zero.workers: 'true'
          dataproc:dataproc.logging.stackdriver.job.driver.enable: 'true'
          dataproc:pip.packages: 'dynaconf==3.2.2,toml==0.10.2,great-expectations==0.18.7'

